name: "Publish Resume"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - ".gitignore"
      - "exports/**"

jobs:
  publish_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install the dependencies
        run: |
          apt-get update && apt-get install -y git
          npm install resume-cli
          npm install https://github.com/negadive/jsonresume-theme-stackoverflow-ibic.git
          mkdir public
      - name: Build the resume - html
        run: |
          npx resume export --theme stackoverflow-ibic --format html public/index.html
      - name: Deploy the resume - html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Allow unprivileged user namespaces (Chromium sandbox)
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Inject phone number
        run: sed -i "s/PHONE_PLACEHOLDER/${{ secrets.PHONE_NUMBER }}/" resume.json
      - name: Build the resume - pdf
        run: |
          npx resume export --theme stackoverflow-ibic --format pdf exports/Teguh_Prabowo_Wijangkoro.pdf
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add exports/Teguh_Prabowo_Wijangkoro.pdf
          git commit -m "Publishing latest PDF"
      - name: Deploy the resume - pdf  
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
